cooperative_transportation_4ws:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  v1_rear_right_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v1_rear_right_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v1_rear_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v1_rear_right_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v1_front_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v1_front_right_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v1_front_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v1_front_left_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v1_rear_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v1_rear_left_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v1_front_right_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v1_front_right_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v1_front_left_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v1_front_left_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v1_rear_left_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v1_rear_left_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  linkage1_rotation_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: linkage1_rotation
    pid: {p: 0.0, i: 0.0, d: 0.}
  linkage2_rotation_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: linkage2_rotation
    pid: {p: 0.0, i: 0.0, d: 0.}
  linkage3_rotation_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: linkage3_rotation
    pid: {p: 0.0, i: 0.0, d: 0.1}
  v2_front_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v2_front_right_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v2_rear_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v2_rear_right_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v2_front_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v2_front_left_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v2_rear_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v2_rear_left_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v2_front_right_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v2_front_right_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v2_rear_right_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v2_rear_right_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v2_front_left_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v2_front_left_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v2_rear_left_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v2_rear_left_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v3_front_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v3_front_right_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v3_rear_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v3_rear_right_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v3_front_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v3_front_left_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v3_rear_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: v3_rear_left_steering
    pid: {p: 1000.0, i: 0.01, d: 0.1}
  v3_front_right_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v3_front_right_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v3_rear_right_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v3_rear_right_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v3_front_left_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v3_front_left_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  v3_rear_left_wheel_rotation_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: v3_rear_left_wheel_rotation
    pid: {p: 800.0, i: 0.01, d: 0.1}
  linkage_point_to_v1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: linkage_point_to_v1
    pid: {p: 0.0, i: 0.0, d: 0.0}
  linkage_point_to_v2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: linkage_point_to_v2
    pid: {p: 0.0, i: 0.0, d: 0.0}
  linkage_point_to_v3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: linkage_point_to_v3
    pid: {p: 0.0, i: 0.0, d: 0.0}
